In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [12]:
df = pd.read_csv ("./emp_attrition.csv")

In [13]:
X = df.drop('Attrition', axis=1)
y = df['Attrition']

In [14]:
# feature extraction
test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(X, y)

In [20]:
np.set_printoptions(precision=3, suppress=True)
print(fit.scores_)

[     84.155       0.        956.58        0.963      63.772       0.521
       6.959       0.         58.12        6.891       0.191       0.432
       4.606      24.939       1.742       7.012      10.81   127922.294
    1196.634       6.439       0.         63.845       0.235       0.001
       1.332       0.         25.269     230.722       3.086       1.086
     142.1       117.523       7.602     110.672]

In [21]:
X

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,1102,1,1,2,1,1,1,2,...,1,80,0,8,0,1,6,4,0,5
1,49,2,279,2,8,1,1,1,2,3,...,4,80,1,10,3,3,10,7,1,7
2,37,1,1373,2,2,2,2,1,4,4,...,2,80,0,7,3,3,0,0,0,0
3,33,2,1392,2,3,4,1,1,5,4,...,3,80,0,8,3,3,8,7,3,0
4,27,1,591,2,2,1,3,1,7,1,...,4,80,1,6,3,3,2,2,2,2
5,32,2,1005,2,2,2,1,1,8,4,...,3,80,0,8,2,2,7,7,3,6
6,59,1,1324,2,3,3,3,1,10,3,...,1,80,3,12,3,2,1,0,0,0
7,30,1,1358,2,24,1,1,1,11,4,...,2,80,1,1,2,3,1,0,0,0
8,38,2,216,2,23,3,1,1,12,4,...,2,80,0,10,2,3,9,7,1,8
9,36,1,1299,2,27,3,3,1,13,3,...,2,80,2,17,3,2,7,7,7,7
10,35,1,809,2,16,3,3,1,14,1,...,3,80,1,6,5,3,5,4,0,3
11,29,1,153,2,15,2,1,1,15,4,...,4,80,0,10,3,3,9,5,0,8
12,31,1,670,2,26,1,1,1,16,1,...,4,80,1,5,1,2,5,2,4,3
13,34,1,1346,2,19,2,3,1,18,2,...,3,80,1,3,2,3,2,2,1,2
14,28,1,103,2,24,3,1,1,19,3,...,2,80,0,6,4,3,4,2,0,3
15,29,1,1389,2,21,4,1,1,20,2,...,3,80,1,10,1,3,10,9,8,8
16,32,1,334,2,5,2,1,1,21,1,...,4,80,2,7,5,2,6,2,0,5
17,22,3,1123,2,16,2,3,1,22,4,...,2,80,2,1,2,2,1,0,0,0
18,53,1,1219,1,2,4,1,1,23,1,...,3,80,0,31,3,3,25,8,3,7
19,38,1,371,2,2,3,1,1,24,4,...,3,80,0,6,3,3,3,2,1,2
20,24,3,673,2,11,2,2,1,26,1,...,4,80,1,5,5,2,4,2,1,3
21,36,1,1218,1,9,4,1,1,27,3,...,2,80,0,10,4,3,5,3,0,3
22,34,1,419,2,7,4,1,1,28,1,...,3,80,0,13,4,3,12,6,2,11
23,21,1,391,2,15,2,1,1,30,3,...,4,80,0,0,6,3,0,0,0,0
24,34,1,699,2,6,1,3,1,31,2,...,3,80,0,8,2,3,4,2,1,3
25,53,1,1282,2,5,3,2,1,32,3,...,4,80,1,26,3,2,14,13,4,8
26,32,2,1125,2,16,1,1,1,33,2,...,2,80,0,10,5,3,10,2,6,7
27,42,1,691,1,8,4,4,1,35,3,...,4,80,1,10,2,3,9,7,4,2
28,44,1,477,2,7,4,3,1,36,1,...,4,80,1,24,4,3,22,6,5,17
29,46,1,705,1,2,4,4,1,38,2,...,4,80,0,22,2,2,2,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1440,36,2,688,2,4,2,1,1,2025,4,...,2,80,3,18,3,3,4,2,0,2
1441,56,3,667,2,1,4,1,1,2026,3,...,1,80,1,13,2,2,13,12,1,9
1442,29,1,1092,2,1,4,3,1,2027,1,...,2,80,3,4,3,4,2,2,2,2
1443,42,1,300,2,2,3,1,1,2031,1,...,1,80,0,24,2,2,22,6,4,14
1444,56,1,310,2,7,2,5,1,2032,4,...,4,80,1,14,4,1,10,9,9,8
1445,41,1,582,2,28,4,1,1,2034,1,...,3,80,1,21,3,3,20,7,0,10
1446,34,1,704,1,28,3,4,1,2035,4,...,4,80,2,8,2,3,8,7,1,7
1447,36,3,301,1,15,4,4,1,2036,4,...,1,80,1,15,4,2,15,12,11,11
1448,41,1,930,1,3,3,1,1,2037,3,...,3,80,1,14,5,3,5,4,0,4
1449,32,1,529,2,2,3,5,1,2038,4,...,4,80,0,4,4,3,4,2,1,2
1450,35,1,1146,3,26,4,1,1,2040,3,...,3,80,0,9,2,3,9,0,1,7
1451,38,1,345,1,10,2,1,1,2041,1,...,3,80,1,10,1,3,10,7,1,9
1452,50,2,878,1,1,4,1,1,2044,2,...,4,80,2,12,3,3,6,3,0,1
1453,36,1,1120,1,11,4,4,1,2045,2,...,1,80,1,8,2,2,6,3,0,0
1454,45,1,374,1,20,3,1,1,2046,4,...,3,80,0,8,3,3,5,3,0,1
1455,40,1,1322,2,2,4,1,1,2048,3,...,4,80,0,8,2,3,2,2,2,2
1456,35,2,1199,2,18,4,1,1,2049,3,...,4,80,2,10,2,4,10,2,0,2
1457,40,1,1194,2,2,4,3,1,2051,3,...,2,80,3,20,2,3,5,3,0,2
1458,35,1,287,2,1,4,1,1,2052,3,...,4,80,1,4,5,3,4,3,1,1
1459,29,1,1378,2,13,2,2,1,2053,4,...,1,80,1,10,2,3,4,3,0,3
1460,29,1,468,2,28,4,3,1,2054,4,...,2,80,0,5,3,1,5,4,0,4
1461,50,1,410,1,28,3,4,1,2055,4,...,2,80,1,20,3,3,3,2,2,0
1462,39,1,722,1,24,1,4,1,2056,2,...,1,80,1,21,2,2,20,9,9,6
1463,31,3,325,2,5,3,3,1,2057,2,...,2,80,0,10,2,3,9,4,1,7
1464,26,1,1167,1,5,3,2,1,2060,4,...,4,80,0,5,2,3,4,2,0,0
1465,36,2,884,2,23,2,3,1,2061,3,...,3,80,1,17,3,3,5,2,0,3
1466,39,1,613,2,6,1,3,1,2062,4,...,1,80,1,9,5,3,7,7,1,7
1467,27,1,155,2,4,3,1,1,2064,2,...,2,80,1,6,0,3,6,2,0,3
1468,49,2,1023,1,2,3,3,1,2065,4,...,4,80,0,17,3,2,9,6,0,8
1469,34,1,628,2,8,3,3,1,2068,2,...,1,80,0,6,3,4,4,3,1,2

In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

In [26]:
model = LogisticRegression()

In [41]:
rfe = RFE(model, 4)
fit = rfe.fit(X, y)

In [42]:
print("Num Features: ", fit.n_features_)
print("Selected Features: ", fit.support_)
print("Feature Ranking: ", fit.ranking_)

Num Features:  4
Selected Features:  [False False False False False False False False False False False False
  True  True False False  True False False False False  True False False
 False False False False False False False False False False]
Feature Ranking:  [22 24 28  2 21 23  9 27 29  5  3 25  1  1 18  4  1 30 31 14 26  1 20  7 10
 19  6 17 13  8 16 11 12 15]

In [44]:
# factors influencing attrition
X.columns[fit.support_]

Index(['JobInvolvement', 'JobLevel', 'MaritalStatus', 'OverTime'], dtype='object')